### ISSUE TITLE
Problema de validação

### ISSUE THREAD

**Issue by jacksonveroneze** [mm75/stormbox-zf-element#1]
1. Não está aparecendo a "*", informando que o campo é requerido.
2. Após submeter o formulário, e o mesmo falhar na validação, não exibe a mensagem de erro do elemento.

**Comment by mm75** [comment]
Ajustes feitos nos elementos.

**Comment by jacksonveroneze** [comment]
Obrigado, funcionou corretamente. Estou fechando a issue.
